// import $ from "jquery"
// import "../components/js/jquery.min.js";
// import "../components/js/popper.min.js";
// import "../components/js/bootstrap.min.js";
// import "../components/js/jquery.appear.js";
// import "../components/js/countdown.min.js";
// import "../components/js/jquery.counterup.min.js";
// import "../components/js/wow.min.js";
// import "../components/js/apexcharts.js";
// import "../components/js/slick.min.js";
// import "../components/js/select2.min.js";
// import "../components/js/owl.carousel.min.js";
// import "../components/js/jquery.magnific-popup.min.js";
// import "../components/js/smooth-scrollbar.js";
// import "../components/js/lottie.js";
// import "../components/js/core.js";
// import "../components/js/charts.js";
// import "../components/js/animated.js";
// import "../components/js/kelly.js";
// import "../components/js/maps.js";
// import "../components/js/worldLow.js";
// // import "../components/js/raphael-min.js";
// import "../components/js/morris.js";
// import "../components/js/morris.min.js";
// import "../components/js/flatpickr.js";
// import "../components/js/style-customizer.js";
// // import "../components/js/chart-custom.js";
// import "../components/js/custom.js";
